# Generated by Django 4.0.4 on 2022-04-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Registros de Entrada',
            },
        ),
        migrations.CreateModel(
            name='Registro_Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_saida', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Registros de Saida',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.CreateModel(
            name='Nota_Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.categoria')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.registro_entrada')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.registro_saida')),
            ],
            options={
                'verbose_name_plural': 'Notas de Saida',
            },
        ),
    ]
