# Generated by Django 4.0.4 on 2022-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_registro_entrada_registro_saida_categoria_valor_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_entrada',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro_saida',
            name='hora_saida',
            field=models.DateTimeField(),
        ),
    ]
