# Generated by Django 4.0.4 on 2022-05-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_registro_entrada_hora_entrada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota_Saida',
        ),
    ]
