# Generated by Django 4.0.4 on 2022-05-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_delete_nota_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.categoria')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.registro_entrada')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.registro_saida')),
            ],
        ),
    ]
