# Generated by Django 4.0.4 on 2022-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='observacoes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
